version: "3.8"

services:
  postgis:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - "../data/postgres:/var/lib/postgresql/data"
  shopalone:
    image: shopalone:latest
    environment:
      - PG_HOST=postgis
      - PG_SCHEMA=shopalone
    ports:
      - "8000:8000"
