version: "3.8"

services:
  postgis:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "../data/postgres:/var/lib/postgresql/data"
  shopalone:
    image: shopalone:latest
    environment:
      - PG_HOST=postgis
      - PG_SCHEMA=shopalone
    ports:
      - "127.0.0.1:8000:8000"
