version: "3.7"

services:
  postgis:
    image: "postgis/postgis:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  shopalone:
    build: .
    ports:
      - 8000:8000
